// from https://wowvendor.com/media/gaming/nightreign-relic/#offensive-relic-effects“

export const relicProperties = [
    'Offensive - Attack power increases after using grease items',
    'Offensive - Attack power up when facing frostbite-afflicted enemy',
    'Offensive - Attack power up when facing poison-afflicted enemy',
    'Offensive - Attack power up when facing scarlet rot-afflicted enemy',
    'Offensive - Boosts Attack Power of Added Affinity Attacks',
    'Offensive - Defeating enemies fills more of the Art gauge',
    'Offensive - Fire Attack Power Up',
    'Offensive - Fire Attack Power Up +1',
    'Offensive - Fire Attack Power Up +2',
    'Offensive - Fire Damage Negation Up',
    'Offensive - Holy Attack Power Up',
    'Offensive - Holy Attack Power Up +1',
    'Offensive - Holy Attack Power Up +2',
    'Offensive - Holy Damage Negation Up',
    'Offensive - Improved Attack Power with 3+ Colossal Weapons Equipped',
    'Offensive - Improved Attack Power with 3+ Curved Swords Equipped',
    'Offensive - Improved Attack Power with 3+ Greataxes Equipped',
    'Offensive - Improved Attack Power with 3+ Greatswords Equipment',
    'Offensive - Improved Attack Power with 3+ Great Spears Equipped',
    'Offensive - Improved Attack Power with 3+ Halberds Equipped',
    'Offensive - Improved Attack Power with 3+ Katanas Equipped',
    'Offensive - Improved Attack Power with 3+ Reapers Equipped',
    'Offensive - Improved Attack Power with 3+ Spears Equipped',
    'Offensive - Improved Attack Power with 3+ Thrusting Swords Equipped',
    'Offensive - Improved Attack Power with 3+ Twinblades Equipped',
    'Offensive - Improved Bestial Incantations',
    'Offensive - Improved Bow Attack Power',
    'Offensive - Improved Carian Sword Sorcery',
    'Offensive - Improved Critical Hits',
    'Offensive - Improved Critical Hits +1',
    'Offensive - Improved Crystalian sorcery',
    'Offensive - Improved Curved Sword Attack Power',
    'Offensive - Improved Dagger Attack Power',
    'Offensive - Improved Dragon Communion Incantations',
    'Offensive - Improved Dragon Cult Incantations',
    'Offensive - Improved Frenzied Flame Incanations',
    'Offensive - Improved Fundamentalist Incantations',
    'Offensive - Improved Giants’ Flame Incantations',
    'Offensive - Improved Glintblade Sorcery',
    'Offensive - Improved Godslayer Incantations',
    'Offensive - Improved Gravity Sorcery',
    'Offensive - Improved Greatsword Attack Power',
    'Offensive - Improved Great Hammer Attack Power',
    'Offensive - Improved Initial Standard Attack',
    'Offensive - Improved Invisibility Sorcery',
    'Offensive - Improved Perfuming Arts',
    'Offensive - Improved Roar & Breath Attacks',
    'Offensive - Improved Stance-Breaking when Two-Handing',
    'Offensive - Improved Stonedigger Sorcery',
    'Offensive - Improved Straight Sword Attack Power',
    'Offensive - Improved Thorn Sorcery',
    'Offensive - Magic Attack Power Up',
    'Offensive - Magic Attack Power Up +1',
    'Offensive - Magic Attack Power Up +2',
    'Offensive - Physical Attack Up',
    'Offensive - Physical Attack Up +1',
    'Offensive - Physical Attack Up +2',
    'Offensive - Standard attacks 1 level stronger',
    'Offensive - Starting armament deals fire damage',
    'Offensive - Starting armament deals holy damage',
    'Offensive - Starting armament deals magic damage',
    'Offensive - Switching Weapons Adds an Affinity Attack',
    'Offensive - Switching Weapons Boosts Attack Power',
    'Offensive - Taking attacks improves attack power',
    'Offensive - Ultimate Art Gauge +1',
    'Offensive - Ultimate Art Gauge +2',
    'Offensive - Ultimate Art Gauge +3',
    'Defensive - Continuous HP Recovery',
    'Defensive - Defeating enemies near Totem Stela restores HP',
    'Defensive - Defeating enemies restores HP for allies but not for self',
    'Defensive - Draw enemy attention while guarding',
    'Defensive - Flask Also Heals Allies',
    'Defensive - Guard counter is given a boost based on current HP',
    'Defensive - HP Recovery From Successful Guarding',
    'Defensive - HP restored when using cured meats, medicinal boluses, etc.',
    'Defensive - HP Restoration upon Claw Attacks',
    'Defensive - HP Restoration upon Curved Sword Attacks',
    'Defensive - HP Restoration upon Greataxe Attacks',
    'Defensive - HP Restoration upon Greatsword Attacks',
    'Defensive - HP Restoration upon Halberd Attacks',
    'Defensive - HP Restoration upon Katana Attacks',
    'Defensive - HP Restoration upon Spear Attacks',
    'Defensive - HP Restoration upon Thrusting Counterattack',
    'Defensive - HP Restoration upon Thrusting Sword Attacks',
    'Defensive - HP Restoration upon Twinblade Attacks',
    'Defensive - HP Restoration upon Whip Attacks',
    'Defensive - Improved Guard Counters',
    'Defensive - Items confer effect to all nearby allies',
    'Defensive - Magic Damage Negation Up',
    'Defensive - Nearby Frostbite Conceals Self',
    'Defensive - Partial HP Restoration upon Post-Damage Attacks',
    'Defensive - Shield Greases in possession at the start of expedition',
    'Defensive - Slowly restore HP for self and nearby allies when HP is low',
    'Defensive - Starting armament deals fire damage',
    'Attribute - Arcane +1',
    'Attribute - Arcane +2',
    'Attribute - Arcane +3',
    'Attribute - Critical Hit Boosts Stamina Recovery Speed',
    'Attribute - Dexterity +1',
    'Attribute - Dexterity +2',
    'Attribute - Dexterity +3',
    'Attribute - Endurance +1',
    'Attribute - Endurance +2',
    'Attribute - Endurance +3',
    'Attribute - Faith +1',
    'Attribute - Faith +2',
    'Attribute - Faith +3',
    'Attribute - FP Restoration upon Claw Attacks',
    'Attribute - FP Restoration upon Curved Greatsword Attacks',
    'Attribute - FP Restoration upon Greataxe Attacks',
    'Attribute - FP Restoration upon Successive Attacks',
    'Attribute - Improved Poise Near Totem Stela',
    'Attribute - Improved Poise & Damage Negation When Knocked Back by Damage',
    'Attribute - Increased Maximum FP',
    'Attribute - Increased Maximum HP',
    'Attribute - Increased Maximum Stamina',
    'Attribute - Intelligence +1',
    'Attribute - Intelligence +2',
    'Attribute - Intelligence +3',
    'Attribute - Madness Continually Recovers FP',
    'Attribute - Max FP permanently increased after releasing Sorcerer’s Rise mechanism',
    'Attribute - Max FP Up with 3+ Sacred Seals Equipped',
    'Attribute - Max FP Up with 3+ Staves Equipped',
    'Attribute - Max HP increased by a portion when guard counter is used',
    'Attribute - Max HP Up with 3+ Greatshields Equipped',
    'Attribute - Max HP Up with 3+ Small Shields',
    'Attribute - Mind +1',
    'Attribute - Mind +2',
    'Attribute - Mind +3',
    'Attribute - Poise +1',
    'Attribute - Poise +2',
    'Attribute - Poise +3',
    'Attribute - Stamina recovers with each successful attack',
    'Attribute - Stamina recovers with each successful attack +1',
    'Attribute - Strength +1',
    'Attribute - Strength +2',
    'Attribute - Strength +3',
    'Attribute - Vigor +1',
    'Attribute - Vigor +2',
    'Attribute - Vigor +3',
    'Status - Attacks Inflict Blood Loss',
    'Status - Attacks Inflict Blood Loss +2',
    'Status - Attacks Inflict Frost',
    'Status - Attacks Inflict Frost +1',
    'Status - Attacks Inflict Frost +2',
    'Status - Attacks Inflict Scarlet Rot',
    'Status - Attacks Inflict Sleep +1',
    'Status - Attacks Inflict Sleep +2',
    'Status - Blood Loss Resistance Up',
    'Status - Gesture “Crossed Legs” Builds Up Madness',
    'Status - Improved Blood Loss Resistance',
    'Status - Improved Death Blight Resistance',
    'Status - Improved Frost Resistance',
    'Status - Improved Madness Resistance',
    'Status - Improved Poison Resistance',
    'Status - Improved Rot Resistance',
    'Status - Improved Sleep Resistance',
    'Status - Lightning Attack Power Up',
    'Status - Lightning Attack Power Up +1',
    'Status - Lightning Attack Power Up +2',
    'Status - Lightning Damage Negation Up',
    'Status - Madness Resistance Up',
    'Status - Poison & Rot in Vicinity Increases Attack Power',
    'Status - Sleep Resistance Up',
    'Status - Starting armament inflicts Poison',
    'Status - Starting armament inflicts Blood Loss', // added
    'Utility - Art gauge charged from successful guarding',
    'Utility - Art gauge fills moderately upon critical hit',
    'Utility - Attack power permanently increased when unlocking an evergaol',
    'Utility - Changes compatible armament’s skill to Chilling Mist at start of expedition',
    'Utility - Changes compatible armament’s skill to Determination at start of expedition',
    'Utility - Changes compatible armament’s skill to Glintblade Phalanx at start of expedition',
    'Utility - Changes compatible armament’s skill to Gravitas at start of expedition',
    'Utility - Changes compatible armament’s skill to Hoarfrost Stomp at start of expedition',
    'Utility - Changes compatible armament’s skill to Lightning Slash at start of expedition',
    'Utility - Changes compatible armament’s skill to Sacred Blade at start of expedition',
    'Utility - Changes compatible armament’s skill to Seppuku at start of expedition',
    'Utility - Changes compatible armament’s skill to Storm Stomp at start of expedition',
    'Utility - Character Skill Cooldown Reduction +1',
    'Utility - Character Skill Cooldown Reduction +2',
    'Utility - Character Skill Cooldown Reduction +3',
    'Utility - Critical hits earn runes',
    'Utility - Defeating enemies fills more of the Arts gauge',
    'Utility - Fire Grease in possession at start of expedition',
    'Utility - Fire Pots in possession at start of expedition',
    'Utility - Gravity Stone Chunks in possession at start of expedition',
    'Utility - Holy Grease in possession at start of expedition',
    'Utility - Huge rune discount for shop purchases while on expedition (20% Cheaper)',
    'Utility - Improved Throwing Knife Damage (+15% Damage)',
    'Utility - Improved Throwing Stone Damage',
    'Utility - Improved Throwing Pot Damage',
    'Utility - Increased rune acquisition for self and allies (+3.5% Runes, Stackable)',
    'Utility - Lightning Grease in possession at start of expedition',
    'Utility - Purchasing this item randomly generates a random Delicate, Polished, or Grand relic',
    'Utility - Rune discount for shop purchases while on expedition',
    'Utility - Small Pouch in possession at start of expedition',
    'Utility - Starlight Shards in possession at start of expedition',
    'Utility - Stonesword Key in possession at start of expedition',
    'Utility - Treasure marked upon map',
    'Utility - Ultimate Arts Gauge +1',
    'Utility - Ultimate Arts Gauge +2',
    'Utility - Wraith Calling Bell in possession at start of expedition',
    'Character - Wylder: Follow-up attacks possible when using Character Skill (greatsword only)',
    'Character - Wylder: Art gauge greatly filled when ability is activated',
    'Character - Wylder: Art activation spreads fire in area',
    'Character - Wylder: +1 additional Character Skill use',
    'Character - Revenant: Trigger ghostflame explosion during Ultimate Art activation',
    'Character - Revenant: Strengthens family and allies when Ultimate Art is activate',
    'Character - Revenant: Power up while fighting alongside family',
    'Character - Revenant: Expend own HP to fully heal nearby allies when activating Art',
    'Character - Recluse: Suffer blood loss and increase attack power upon Art activation',
    'Character - Recluse: Collecting affinity residue activates Terra Magica',
    'Character - Recluse: Activating Ultimate Art raises Max HP',
    'Character - Raider: Damage taken while using Character Skill improves attack power and stamina',
    'Character - Ironeye: Extends duration of weak point',
    'Character - Ironeye: Boosts thrusting counterattacks after executing Art',
    'Character - Guardian: Slowly restores nearby allies’ HP while Art is active',
    'Character - Guardian: Reflect a portion of damage received when ability is activated',
    'Character - Guardian: Increased duration for Character Skill',
    'Character - Guardian: Damage negation for allies improved when using Character Skills',
    'Character - Guardian: Creates whirlwind when charging halberd attacks',
    'Character - Executor: While Character Skill is active, unlocking use of cursed sword restores HP',
    'Character - Executor: Roaring restores HP while Art is active',
    'Character - Executor: Character Skill Boosts Attack but Attacking Drains HP',
    'Character - Duchess: Last hit of chain attack reprises upon nearby enemies',
    'Character - Duchess: Improved Character Skill Attack Power',
    'Character - Duchess: Defeating enemies while Art is active ups attack power',
    'Character - Duchess: Dagger chain attack reprises event upon enemies',
    'Character - Duchess: Becomes difficult to spot and silenced footsteps after landing critical from behind',
] as const;

export type RelicProperties = (typeof relicProperties)[keyof typeof relicProperties];
